language: cpp
sudo: required
services:
  - docker

before_install:
  - docker pull yitsushi/cpp-commander

install:
  - gem install coveralls-lcov

script:
  - docker run --rm -v `pwd`:`pwd` -w `pwd` yitsushi/cpp-commander ./build-and-run.sh

after_success:
  - coveralls-lcov --repo-token ${COVERALLS_TOKEN} coverage.info.cleaned
