language: cpp
sudo: required
services:
  - docker

before_install:
  - docker pull yitsushi/cpp-commander

install:
  - gem install coveralls-lcov

script:
  - docker run --rm -e COVERALLS_TOKEN=${COVERALLS_TOKEN} -e TRAVIS_JOB_ID=${TRAVIS_JOB_ID} -v $(pwd):/code yitsushi/cpp-commander

